// <auto-generated />
namespace Exam2.Migrations.StudentMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModelValidationandDisplay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelValidationandDisplay));
        
        string IMigrationMetadata.Id
        {
            get { return "201901091201357_Model Validation and Display"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
